- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# # gz topic published by thrusters JointState plugin
# - ros_topic_name: "thrusters/joint_states"
#   gz_topic_name: "thrusters/joint_states"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "gz.msgs.Model"
#   direction: GZ_TO_ROS

# # gz topic published by Arm JointState plugin
# - ros_topic_name: "arm/joint_states"
#   gz_topic_name: "arm/joint_states"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "gz.msgs.Model"
#   direction: GZ_TO_ROS

# gz topic published by JointState plugin
- ros_topic_name: "/joint_states"
  gz_topic_name: "/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# map ros to gz topic for thusters
- ros_topic_name: "rov_ricketts/front_left_thrust"
  gz_topic_name: "/model/rov_ricketts/joint/front_left_thruster/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "rov_ricketts/front_right_thrust"
  gz_topic_name: "/model/rov_ricketts/joint/front_right_thruster/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "rov_ricketts/rear_left_thrust"
  gz_topic_name: "/model/rov_ricketts/joint/rear_left_thruster/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "rov_ricketts/rear_right_thrust"
  gz_topic_name: "/model/rov_ricketts/joint/rear_right_thruster/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "rov_ricketts/up_rear_thrust"
  gz_topic_name: "/model/rov_ricketts/joint/up_rear_thruster/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "rov_ricketts/up_front_left_thrust"
  gz_topic_name: "/model/rov_ricketts/joint/up_front_left_thruster/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "rov_ricketts/up_front_right_thrust"
  gz_topic_name: "/model/rov_ricketts/joint/up_front_right_thruster/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# map from ros to gz topic for buoyancy
- ros_topic_name: "rov_ricketts/buoyancy"
  gz_topic_name: "/model/rov_ricketts/buoyancy_engine"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# map from gz to ros topic for odometry
- ros_topic_name: "rov_ricketts/odometry"
  gz_topic_name: "/model/rov_ricketts/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# map from gz to ros topic for Sonar
- ros_topic_name: "rov_ricketts/sonar"
  gz_topic_name: "/sonar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "rov_ricketts/sonar/points"
  gz_topic_name: "/sonar/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "camera/camera_info"
  gz_topic_name: "camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS


- ros_topic_name: "depth_camera/depth_image"
  gz_topic_name: "depth_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "depth_camera/points"
  gz_topic_name: "depth_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: "GZ_TO_ROS"

- ros_topic_name: "gripper_camera/camera_info"
  gz_topic_name: "gripper_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: "GZ_TO_ROS"
